### ISSUE TITLE
I want to ask why you replaced the wifi card? both card is ac and similar specs? thanks

### ISSUE THREAD

**Issue by kocoman1** [MuertoGB/MacBook-Wi-Fi-DXE-Patching#1]
I want to ask why you replaced the wifi card? both card is ac and similar specs? thanks

**Comment by MuertoGB** [comment]
Back in my early days of board repair, me and another encountered the issue of having an incorrect Wi-Fi not working in recovery mode, however we did not realise the Wi-Fi card was incorrect and were walking in circles for a couple hours.

The research is here out of curiosity derived from that moment.
